### ISSUE TITLE
Permissions Error

### ISSUE THREAD

**Issue by triiq** [milktoastlab/SolanaNFTBot#17]
Hello, this repo is awesome! I keep having the same error come up though. I followed the permissions stated in the readme but still seem to be having issues.

Logged in as ApeFood Sales Bot#4584!
starting 1 worker(s)...
DiscordAPIError: Missing Access
    at RequestHandler.execute (/root/SolanaNFTBot/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/root/SolanaNFTBot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async ChannelManager.fetch (/root/SolanaNFTBot/node_modules/discord.js/src/managers/ChannelManager.js:114:18)
    at async Object.execute (/root/SolanaNFTBot/src/workers/notifyNFTSalesWorker.ts:28:24)
    at async /root/SolanaNFTBot/src/workers/initWorkers.ts:18:16
    at async Promise.all (index 0) {
  method: 'get',
  path: '/channels/920378265393315931',
  code: 50001,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }
}

**Comment by kryptoj** [comment]
It should work if you have the right permissions setup. Make sure the bot has access to the channel? Sometimes the channel needs to give the bots access as well.

**Comment by triiq** [comment]
Thank you! I'll check it out again!

**Comment by triiq** [comment]
Killer stuff!
